---
_:
  indent_char: " "
  indent_size: 2
TypeScript:
  indent_char: " "
  indent_size: 2
  end_with_comma: true
  wrap_line_length: 80
  end_with_semicolon: true
  arrow_parens: "as-needed"
  convert_quotes: "double"
  object_curly_spacing: true
# JavaScript:
#   indent_char: " "
#   indent_size: 2
CSS:
  indent_char: " "
  indent_size: 2
HTML:
  indent_char: " "
  indent_size: 2